version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      versioning-strategy: 'increase-if-necessary'
      groups:
          eslint:
              patterns:
                  - 'eslint'
                  - '@eslint/*'
                  - 'eslint-*'
                  - '@typescript-eslint/*'
                  - 'typescript-eslint'
                  - 'vue-eslint-parser'
      commit-message:
          prefix: 'chore(deps)'
      open-pull-requests-limit: 5

    - package-ecosystem: 'npm'
      directory: '/client'
      schedule:
          interval: 'weekly'
      versioning-strategy: 'increase-if-necessary'
      groups:
          eslint:
              patterns:
                  - 'eslint'
                  - '@eslint/*'
                  - 'eslint-*'
                  - '@typescript-eslint/*'
                  - 'typescript-eslint'
                  - 'vue-eslint-parser'
          fontawesome:
              patterns:
                  - '@fortawesome/*'
          vitest:
              patterns:
                  - 'vitest'
                  - '@vitest/*'
          vue:
              patterns:
                  - 'vue'
                  - '@vue/compiler-sfc'
      commit-message:
          prefix: 'chore(deps)'
      open-pull-requests-limit: 5

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      commit-message:
          prefix: 'chore(ci)'
      open-pull-requests-limit: 3
