name: 'Prepare NPM job'
runs:
    using: 'composite'
    steps:
        - name: Restore node modules cache
          uses: actions/cache@v4
          with:
              path: ${{ env.CACHE_PATHS }}
              key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
              restore-keys: |
                  ${{ runner.os }}-node_modules-
