name: 'Prepare NPM job'
runs:
    using: 'composite'
    steps:
        - name: Restore node modules cache
          uses: actions/cache@v4
          with:
              path: ${{ env.CACHE_PATHS }}
              key: ${{ env.CACHE_KEY }}
              restore-keys: ${{ env.CACHE_RESTORE_KEYS }}
